###GET User
GET http://localhost:1337/api/auth

###
////////////////////////////////////////////////////////

###GET User particulier
GET http://localhost:1337/api/auth/2
Content-Type: application/json

###
////////////////////////////////////////////////////////

###POST User
POST http://localhost:1337/api/auth/register
Content-Type: application/json

{
    "data": {
        "email": "sabrinah_38@hotmail.com",
        "password": "kiwi",
        "firstName": "Sabrina",
        "lastName": "Hammadi"
    }
}

###
////////////////////////////////////////////////////////

###login users
POST http://localhost:1337/api/auth/login
Content-Type: application/json

{
    "data": {
        "email": "sabrinah_38@hotmail.com",
        "password": "kiwi"
    }
}

###
////////////////////////////////////////////////////////

###DELETE Student particulier
DELETE http://localhost:1337/api/auth/3
Content-Type: application/json

