###GET ClassRooms
GET http://localhost:1337/api/classRooms

###
////////////////////////////////////////////////////////

###GET ClassRoom particulier
GET http://localhost:1337/api/classRooms/1
Content-Type: application/json

###
////////////////////////////////////////////////////////

###POST students
POST http://localhost:1337/api/classRooms
Content-Type: application/json

{
    "data": {
      "name": "DIGITAL-B3"
    }
}
###
////////////////////////////////////////////////////////

###PUT students
PUT http://localhost:1337/api/classRooms/1
Content-Type: application/json

{
    "data": {
        "name": "DEV-B3"
    }
}

###
////////////////////////////////////////////////////////

###DELETE Student particulier
DELETE http://localhost:1337/api/classRooms/3
Content-Type: application/json

