###GET User
GET http://localhost:1337/api/auth

###
////////////////////////////////////////////////////////

###GET User particulier
GET http://localhost:1337/api/auth/2
Content-Type: application/json

###
////////////////////////////////////////////////////////

###POST User
POST http://localhost:1337/api/auth/register
Content-Type: application/json

{
    "data": {
        "firstname": "Maitresse",
        "lastname": "Du_Temps",
        "mtp": "temps"
    }
}
###
////////////////////////////////////////////////////////

###PUT users
PUT http://localhost:1337/api/auth/3
Content-Type: application/json

{
    "data": {
        "firstname": "Maitre",
        "lastname": "Du_Temps",
        "mtp": "temps"
    }
}

###
////////////////////////////////////////////////////////

###DELETE Student particulier
DELETE http://localhost:1337/api/auth/3
Content-Type: application/json

